FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

RUN apt-get update && apt install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive
RUN apt-get update && apt-get install -y \
    linux-libc-dev \
    manpages-dev \
    python-dev \
    golang-1.10-go \
    git \
    curl \
    patch \
    pkg-config \
    zip \
    g++ \
    zlib1g-dev \
    unzip \
    python \
    wget 

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin

RUN go get -u github.com/kardianos/govendor
RUN git clone https://github.com/tensorflow/tensorflow.git /tensorflow
WORKDIR /tensorflow
RUN git pull && git checkout v1.13.1

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-installer-linux-x86_64.sh
RUN chmod +x bazel-0.19.2-installer-linux-x86_64.sh
RUN ./bazel-0.19.2-installer-linux-x86_64.sh --user
RUN export PATH="$PATH:$HOME/bin"

RUN yes "" | ./configure

RUN /root/bin/bazel build --config=mkl --config=monolithic //tensorflow:libtensorflow.so
RUN cp bazel-bin/tensorflow/libtensorflow.so /usr/local/lib
RUN cp /root/.cache/bazel/_bazel_root/*/external/mkl_linux/lib/* /usr/local/lib
RUN ldconfig
RUN ln -s /tensorflow/tensorflow /usr/local/include/tensorflow
